<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZFrmWNP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZFrmWNP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZFrmWNP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZFrmWNP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZFrmWNP\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZFrmWNP',
    'container.build_id' => '11fa7573',
    'container.build_time' => 1710379900,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZFrmWNP');
